### ISSUE TITLE
Feature request for  packet data flow

### ISSUE THREAD

**Issue by SpudGunMan** [pdxlocations/curses-client-for-meshtastic#2]
First cool client; second requesting a split window with main chat window. To print each packet to make this look more awesome and to monitor the network with one tool

Basically shim a print packets flying past for enjoyment

**Comment by pdxlocations** [comment]
Thanks!  Hmm, interesting idea.  I'm a little constrained due to some users having smaller displays.  Curses flips out and crashes when things don't fit.  Perhaps a 'one line' packet description: from/to/type?  I don't think I'd want it enabled by default but there could be a flag in the source, or a keystroke perhaps.

**Comment by SpudGunMan** [comment]
Yea. Agree not there by default. 

It just gives a little extra flair to the display to have some rolling code.
